#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# stim_to_cudaq_py.py
# Usage: python stim_to_cudaq_py.py input.stim [output.py]

import sys
import re
import argparse

def process_stim_circuit(stim_lines: list[str]) -> str:
    """
    Processes a list of Stim circuit lines and generates the corresponding
    CUDA-Q Python kernel as a single string.

    Args:
        stim_lines: A list of strings, where each string is a line from the
                    input Stim circuit file.

    Returns:
        A single string containing the full CUDA-Q Python script.
    """
    output_lines = []
    #max_qubit_index = -1

    # First pass to determine the number of qubits required.
    # We find the maximum qubit index mentioned in the circuit.
    #for line in stim_lines:
    #    for num_str in re.findall(r'\d+', line):
    #        max_qubit_index = max(max_qubit_index, int(num_str))

    #num_qubits = max_qubit_index
    
    # -----------------------------------------------------------
    # Generate the CUDA-Q Python script preamble
    # -----------------------------------------------------------
    output_lines.append("#!/usr/bin/env python3")
    output_lines.append("# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.")
    output_lines.append("# SPDX-License-Identifier: Apache-2.0")
    output_lines.append("# autogenerated by stim_to_cudaq_py.py")
    output_lines.append("import sys")
    output_lines.append("import cudaq")
    output_lines.append("")
    output_lines.append("cudaq.set_target('tensornet')")
    output_lines.append("")
    output_lines.append("@cudaq.kernel")
    output_lines.append("def stim_kernel(num_qubits: int):")
    
    # Qubit allocation based on the max index found.
    # This is done once at the beginning of the kernel.
    output_lines.append(f"    q = cudaq.qvector(num_qubits)")
    
    # -----------------------------------------------------------
    # Parse each line and generate the corresponding CUDA-Q code
    # -----------------------------------------------------------
    for line in stim_lines:
        line = line.strip()
        
        # Comments
        match = re.match(r'^#(.*)', line)
        if match:
            output_lines.append(f"    #{match.group(1).strip()}")
            continue

        # DEPOLARIZE1
        match = re.match(r'^DEPOLARIZE1\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    cudaq.apply_noise(cudaq.Depolarization1, {prob}, q[{num}])")
            continue

        # X gate
        match = re.match(r'^X\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    x(q[{num}])")
            continue

        # Y gate
        match = re.match(r'^Y\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    y(q[{num}])")
            continue

        # Z gate
        match = re.match(r'^Z\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    z(q[{num}])")
            continue
            
        # H gate
        match = re.match(r'^H\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    h(q[{num}])")
            continue

        # T gate
        match = re.match(r'^T\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    t(q[{num}])")
            continue

        # RX gate
        match = re.match(r'^RX\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    rx({param}, q[{num}])")
            continue

        # RY gate
        match = re.match(r'^RY\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    ry({param}, q[{num}])")
            continue

        # RZ gate
        match = re.match(r'^RZ\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    rz({param}, q[{num}])")
            continue

        # C_XYZ Gate
        match = re.match(r'^C_XYZ\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    u3(np.pi/2, 0, 0, q[{num}])")
                output_lines.append(f"    rz(np.pi/2, q[{num}])")
            continue
            
        # DEPOLARIZE2
        match = re.match(r'^DEPOLARIZE2\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    cudaq.apply_noise(cudaq.Depolarization2, {prob}, q[{q1}], q[{q2}])")
            continue
            
        # CX (Controlled-X)
        match = re.match(r'^CX\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    x.ctrl(q[{q1}], q[{q2}])")
            continue

        # CY (Controlled-Y)
        match = re.match(r'^CY\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    y.ctrl(q[{q1}], q[{q2}])")
            continue

        # CZ (Controlled-Z)
        match = re.match(r'^CZ\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    z.ctrl(q[{q1}], q[{q2}])")
            continue

        # CH (Controlled-H)
        match = re.match(r'^CH\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    h.ctrl(q[{q1}], q[{q2}])")
            continue

        # CRX (Controlled-RX)
        match = re.match(r'^CRX\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    rx.ctrl({param}, q[{q1}], q[{q2}])")
            continue
            
        # X_ERROR
        match = re.match(r'^X_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    cudaq.apply_noise(cudaq.XError, {prob}, q[{num}])")
            continue

        # Y_ERROR
        match = re.match(r'^Y_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    cudaq.apply_noise(cudaq.YError, {prob}, q[{num}])")
            continue

        # Z_ERROR
        match = re.match(r'^Z_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    cudaq.apply_noise(cudaq.ZError, {prob}, q[{num}])")
            continue

        # R Reset
        match = re.match(r'^R\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    reset(q[{num}])")
            continue
            
        # MR (Measure and Reset)
        match = re.match(r'^MR\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    mz(q[{num}])")
                output_lines.append(f"    reset(q[{num}])")
            continue
            
        # M (Measure)
        match = re.match(r'^M\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    mz(q[{num}])")
            continue
            
        # DETECTOR and OBSERVABLE_INCLUDE are non-native CUDA-Q ops.
        # We will comment them out for now.
        
        # DETECTOR
        match = re.match(r'^DETECTOR\((.*?)\)\s+(.*)', line)
        if match:
            det_loc, det_indices = match.groups()
            output_lines.append(f"    # stim.circuit.append('DETECTOR', [{det_indices}], [{det_loc}])")
            continue
            
        # OBSERVABLE_INCLUDE
        match = re.match(r'^OBSERVABLE_INCLUDE\((.*?)\)\s+(.*)', line)
        if match:
            obs_label, obs_indices = match.groups()
            output_lines.append(f"    # stim.circuit.append('OBSERVABLE_INCLUDE', [{obs_indices}], [{obs_label}])")
            continue

        # FORMALLY SKIPPING QUBIT_COORDS
        match = re.match(r'^QUBIT_COORDS\((.*?)\)\s+(.*)', line)
        if match:
            continue

        # FORMALLY SKIPPING SHIFT_COORDS
        match = re.match(r'^SHIFT_COORDS\((.*?)\)', line)
        if match:
            continue

        # FORMALLY SKIPPING TICKS
        match = re.match(r'^TICK', line)
        if match:
            continue

        # UNLISTED FUNCTION
        print('The following line is not listed: ' + line)

    # -----------------------------------------------------------
    # Add the main execution block
    # -----------------------------------------------------------
    output_lines.append("")
    output_lines.append("if __name__ == '__main__':")
    output_lines.append("    import time")
    output_lines.append("    num_qubits = int(sys.argv[1])")
    output_lines.append("    shots = int(sys.argv[2])")
    output_lines.append("")
    output_lines.append("    # 1. Setup timing")
    output_lines.append("    t_setup_start = time.perf_counter()")
    output_lines.append("    noise_model = cudaq.NoiseModel()")
    output_lines.append("    t_setup_end = time.perf_counter()")
    output_lines.append("")
    output_lines.append("    # 2. Actual sampling")
    output_lines.append("    t_sample_start = time.perf_counter()")
    output_lines.append("    counts = cudaq.sample(stim_kernel, num_qubits, shots_count=shots, noise_model=noise_model)")
    output_lines.append("    t_sample_end = time.perf_counter()")
    output_lines.append("")
    output_lines.append("    # Print timing results")
    output_lines.append("    time_setup = t_setup_end - t_setup_start")
    output_lines.append("    time_sample = t_sample_end - t_sample_start")
    output_lines.append("    time_total = t_sample_end - t_setup_start")
    output_lines.append("")
    output_lines.append("    print()")
    output_lines.append("    print('=== CUDA-Q Timing Breakdown ===')")
    output_lines.append("    print(f'  Setup time:           {time_setup:.6f}s')")
    output_lines.append("    print(f'  Sample time:          {time_sample:.6f}s')")
    output_lines.append("    print(f'  Total time:           {time_total:.6f}s')")
    output_lines.append("    print(f'  Per-shot time:        {time_sample / shots:.6f}s')")
    output_lines.append("    print()")
    output_lines.append("    print('=== CUDA-Q Results ===')")
    output_lines.append("    print(f'  Total number of distinct CUDA-Q shots collected:       {len(counts)}')")
    output_lines.append("    print(f'  Total number of distinct pieces of unlabeled CUDA-Q training data collected:       {len(counts)}')")
    output_lines.append("    print(f'  Total number of overall CUDA-Q shots collected:          {sum(counts.values())}')")
    return "\n".join(output_lines)

def main():
    """Main function to handle command-line arguments and file processing."""
    parser = argparse.ArgumentParser(description='Convert a Stim circuit file to a CUDA-Q Python script.')
    parser.add_argument('input_file', help='Path to the input Stim file.')
    parser.add_argument('output_file', nargs='?', help='Path to the output CUDA-Q Python file. If not provided, output is sent to stdout.')
    args = parser.parse_args()

    try:
        with open(args.input_file, 'r') as f:
            stim_lines = f.readlines()
    except FileNotFoundError:
        print(f"Error: Input file '{args.input_file}' not found.")
        sys.exit(1)

    python_script_content = process_stim_circuit(stim_lines)

    if args.output_file:
        try:
            with open(args.output_file, 'w') as f:
                f.write(python_script_content)
            print(f"Python output written to: {args.output_file}")
        except IOError as e:
            print(f"Error writing to output file '{args.output_file}': {e}")
            sys.exit(1)
    else:
        print(python_script_content)

if __name__ == '__main__':
    main()
