#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# stim_to_pts.py
# Usage: python stim_to_pts.py input.stim [output.py]

import sys
import re
import argparse

def process_stim_circuit(stim_lines: list[str]) -> str:
    """
    Processes a list of Stim circuit lines and generates the corresponding
    CUDA-Q Python kernel as a single string.

    Args:
        stim_lines: A list of strings, where each string is a line from the
                    input Stim circuit file.

    Returns:
        A single string containing the full CUDA-Q Python script.
    """
    output_lines = []
    max_qubit_index = -1

    # First pass to determine the number of qubits required.
    # We find the maximum qubit index mentioned in the circuit.
    for line in stim_lines:
        for num_str in re.findall(r'\d+', line):
            max_qubit_index = max(max_qubit_index, int(num_str))

    num_qubits = max_qubit_index + 1
    
    # -----------------------------------------------------------
    # Generate the CUDA-Q Python script preamble
    # -----------------------------------------------------------
    output_lines.append("#!/usr/bin/env python3")
    output_lines.append("# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.")
    output_lines.append("# SPDX-License-Identifier: Apache-2.0")
    output_lines.append("# autogenerated by stim_to_pts.py")
    output_lines.append("import sys")
    output_lines.append("import os")
    output_lines.append("sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))")
    output_lines.append("import pts")
    output_lines.append("import pickle")
    output_lines.append("")
    output_lines.append("def pts_operators():")
    output_lines.append("    kraus_list = []")
    
    # Qubit allocation based on the max index found.
    # This is done once at the beginning of the kernel.
    
    # -----------------------------------------------------------
    # Parse each line and generate the corresponding CUDA-Q code
    # -----------------------------------------------------------
    ko_line = 0
    for line in stim_lines:
        line = line.strip()
        
        # Comments
        match = re.match(r'^#(.*)', line)
        if match:
            output_lines.append(f"    #{match.group(1).strip()}")
            continue

        # DEPOLARIZE1
        match = re.match(r'^DEPOLARIZE1\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    pts.Depolarization1(kraus_list, {ko_line}, {num}, {prob})")
            ko_line += 1
            continue
            
        # H gate
        match = re.match(r'^H\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # h(q[{num}])")
            continue

        # T gate
        match = re.match(r'^T\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # t(q[{num}])")
            continue

        # X gate
        match = re.match(r'^X\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # x(q[{num}])")
            continue

        # Y gate
        match = re.match(r'^Y\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # y(q[{num}])")
            continue

        # Z gate
        match = re.match(r'^Z\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # z(q[{num}])")
            continue

        # RX gate
        match = re.match(r'^RX\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # rx({param}, q[{num}])")
            continue

        # RY gate
        match = re.match(r'^RY\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # ry({param}, q[{num}])")
            continue

        # RZ gate
        match = re.match(r'^RZ\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # rz({param}, q[{num}])")
            continue

        # C_XYZ Gate
        match = re.match(r'^C_XYZ\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # s(q[{num}])")
                output_lines.append(f"    # s(q[{num}])")
                output_lines.append(f"    # s(q[{num}])")
                output_lines.append(f"    # h(q[{num}])")
            continue
            
        # DEPOLARIZE2
        match = re.match(r'^DEPOLARIZE2\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    pts.Depolarization2(kraus_list, {ko_line}, {q1}, {q2}, {prob})")
            ko_line += 1
            continue
            
        # CX (Controlled-X)
        match = re.match(r'^CX\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    # x.ctrl(q[{q1}], q[{q2}])")
            continue

        # CY (Controlled-Y)
        match = re.match(r'^CY\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    # y.ctrl(q[{q1}], q[{q2}])")
            continue

        # CZ (Controlled-Z)
        match = re.match(r'^CZ\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    # z.ctrl(q[{q1}], q[{q2}])")
            continue

        # CH (Controlled-H)
        match = re.match(r'^CH\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    # h.ctrl(q[{q1}], q[{q2}])")
            continue

        # CRX (Controlled-RX)
        match = re.match(r'^CRX\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    # rx.ctrl({param}, q[{q1}], q[{q2}])")
            continue
            
        # X_ERROR
        match = re.match(r'^X_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    pts.XError(kraus_list, {ko_line}, {num}, {prob})")
            ko_line += 1
            continue

        # Y_ERROR
        match = re.match(r'^Y_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    pts.YError(kraus_list, {ko_line}, {num}, {prob})")
            ko_line += 1
            continue

        # Z_ERROR
        match = re.match(r'^Z_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    pts.ZError(kraus_list, {ko_line}, {num}, {prob})")
            ko_line += 1
            continue

        # R Reset
        match = re.match(r'^R\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # reset(q[{num}])")
            continue
            
        # MR (Measure and Reset)
        match = re.match(r'^MR\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # mz(q[{num}])")
                output_lines.append(f"    # reset(q[{num}])")
            continue
            
        # M (Measure)
        match = re.match(r'^M\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    # mz(q[{num}])")
            continue
            
        # DETECTOR and OBSERVABLE_INCLUDE are non-native CUDA-Q ops.
        # We will comment them out for now.
        
        # DETECTOR
        match = re.match(r'^DETECTOR\((.*?)\)\s+(.*)', line)
        if match:
            det_loc, det_indices = match.groups()
            output_lines.append(f"    # stim.circuit.append('DETECTOR', [{det_indices}], [{det_loc}])")
            continue
            
        # OBSERVABLE_INCLUDE
        match = re.match(r'^OBSERVABLE_INCLUDE\((.*?)\)\s+(.*)', line)
        if match:
            obs_label, obs_indices = match.groups()
            output_lines.append(f"    # stim.circuit.append('OBSERVABLE_INCLUDE', [{obs_indices}], [{obs_label}])")
            continue

        # FORMALLY SKIPPING QUBIT_COORDS
        match = re.match(r'^QUBIT_COORDS\((.*?)\)\s+(.*)', line)
        if match:
            continue

        # FORMALLY SKIPPING SHIFT_COORDS
        match = re.match(r'^SHIFT_COORDS\((.*?)\)', line)
        if match:
            continue

        # FORMALLY SKIPPING TICKS
        match = re.match(r'^TICK', line)
        if match:
            continue

        # UNLISTED FUNCTION
        print('The following line is not listed: ' + line)

    output_lines.append("    return kraus_list")

    # -----------------------------------------------------------
    # Add the main execution block
    # -----------------------------------------------------------
    output_lines.append("")
    output_lines.append("if __name__ == '__main__':")
    output_lines.append("    samples = int(sys.argv[1])")
    output_lines.append("    shots = int(sys.argv[2])")
    output_lines.append("")
    output_lines.append("    kraus_list = pts_operators()")
    output_lines.append("    error_sets = pts.pts_proportional(kraus_list, samples, shots, keep_all_trajectories=True)")
    output_lines.append("    with open('error_sets.pickle', 'wb') as file:")
    output_lines.append("        pickle.dump(error_sets, file)")

    return "\n".join(output_lines)

def main():
    """Main function to handle command-line arguments and file processing."""
    parser = argparse.ArgumentParser(description='Convert a Stim circuit file to a CUDA-Q Python script.')
    parser.add_argument('input_file', help='Path to the input Stim file.')
    parser.add_argument('output_file', nargs='?', help='Path to the output CUDA-Q Python file. If not provided, output is sent to stdout.')
    args = parser.parse_args()

    try:
        with open(args.input_file, 'r') as f:
            stim_lines = f.readlines()
    except FileNotFoundError:
        print(f"Error: Input file '{args.input_file}' not found.")
        sys.exit(1)

    python_script_content = process_stim_circuit(stim_lines)

    if args.output_file:
        try:
            with open(args.output_file, 'w') as f:
                f.write(python_script_content)
            print(f"Python output written to: {args.output_file}")
        except IOError as e:
            print(f"Error writing to output file '{args.output_file}': {e}")
            sys.exit(1)
    else:
        print(python_script_content)

if __name__ == '__main__':
    main()
