#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

# stim_to_be.py
# Usage: python stim_to_be.py input.stim [output.py]

import sys
import re
import argparse

def process_stim_circuit(stim_lines: list[str], num_qubits: int) -> str:
    """
    Processes a list of Stim circuit lines and generates the corresponding
    CUDA-Q Python kernel as a single string.

    Args:
        stim_lines: A list of strings, where each string is a line from the
                    input Stim circuit file.

    Returns:
        A single string containing the full CUDA-Q Python script.
    """
    output_lines = []
    
    # -----------------------------------------------------------
    # Generate the CUDA-Q Python script preamble
    # -----------------------------------------------------------
    output_lines.append("#!/usr/bin/env python3")
    output_lines.append("# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.")
    output_lines.append("# SPDX-License-Identifier: Apache-2.0")
    output_lines.append("# autogenerated by stim_to_be.py")
    output_lines.append("")
    output_lines.append("import cudaq")
    output_lines.append("")
    output_lines.append("@cudaq.kernel")
    output_lines.append("def beXError(kraus_op: int, qubit: cudaq.qubit):")
    output_lines.append("    if kraus_op == 1:")
    output_lines.append("        x(qubit)")
    output_lines.append("")
    output_lines.append("@cudaq.kernel")
    output_lines.append("def beYError(kraus_op: int, qubit: cudaq.qubit):")
    output_lines.append("    if kraus_op == 2:")
    output_lines.append("        y(qubit)")
    output_lines.append("")
    output_lines.append("@cudaq.kernel")
    output_lines.append("def beZError(kraus_op: int, qubit: cudaq.qubit):")
    output_lines.append("    if kraus_op == 3:")
    output_lines.append("        z(qubit)")
    output_lines.append("")
    output_lines.append("@cudaq.kernel")
    output_lines.append("def beDepolarization1(kraus_op: int, qubit: cudaq.qubit):")
    output_lines.append("    if kraus_op == 1:")
    output_lines.append("        x(qubit)")
    output_lines.append("    elif kraus_op == 2:")
    output_lines.append("        y(qubit)")
    output_lines.append("    elif kraus_op == 3:")
    output_lines.append("        z(qubit)")
    output_lines.append("")
    output_lines.append("@cudaq.kernel")
    output_lines.append("def beDepolarization2(kraus_op1: int, kraus_op2: int, qubit1: cudaq.qubit, qubit2: cudaq.qubit):")
    output_lines.append("    if (kraus_op1==1) and (kraus_op2==1):")
    output_lines.append("        x(qubit2)")
    output_lines.append("    elif (kraus_op1==2) and (kraus_op2==2):")
    output_lines.append("        y(qubit2)")
    output_lines.append("    elif (kraus_op1==3) and (kraus_op2==3):")
    output_lines.append("        z(qubit2)")
    output_lines.append("    elif (kraus_op1==4) and (kraus_op2==4):")
    output_lines.append("        x(qubit1)")
    output_lines.append("    elif (kraus_op1==5) and (kraus_op2==5):")
    output_lines.append("        x(qubit1)")
    output_lines.append("        x(qubit2)")
    output_lines.append("    elif (kraus_op1==6) and (kraus_op2==6):")
    output_lines.append("        x(qubit1)")
    output_lines.append("        y(qubit2)")
    output_lines.append("    elif (kraus_op1==7) and (kraus_op2==7):")
    output_lines.append("        x(qubit1)")
    output_lines.append("        z(qubit2)")
    output_lines.append("    elif (kraus_op1==8) and (kraus_op2==8):")
    output_lines.append("        y(qubit1)")
    output_lines.append("    elif (kraus_op1==9) and (kraus_op2==9):")
    output_lines.append("        y(qubit1)")
    output_lines.append("        x(qubit2)")
    output_lines.append("    elif (kraus_op1==10) and (kraus_op2==10):")
    output_lines.append("        y(qubit1)")
    output_lines.append("        y(qubit2)")
    output_lines.append("    elif (kraus_op1==11) and (kraus_op2==11):")
    output_lines.append("        y(qubit1)")
    output_lines.append("        z(qubit2)")
    output_lines.append("    elif (kraus_op1==12) and (kraus_op2==12):")
    output_lines.append("        z(qubit1)")
    output_lines.append("    elif (kraus_op1==13) and (kraus_op2==13):")
    output_lines.append("        z(qubit1)")
    output_lines.append("        x(qubit2)")
    output_lines.append("    elif (kraus_op1==14) and (kraus_op2==14):")
    output_lines.append("        z(qubit1)")
    output_lines.append("        y(qubit2)")
    output_lines.append("    elif (kraus_op1==15) and (kraus_op2==15):")
    output_lines.append("        z(qubit1)")
    output_lines.append("        z(qubit2)")
    output_lines.append("")
    output_lines.append("@cudaq.kernel")
    output_lines.append("def be_kernel(num_qubits: int, kraus_list: list[int]):")
    output_lines.append(f"    q = cudaq.qvector({num_qubits})")
    
    # Qubit allocation based on the max index found.
    # This is done once at the beginning of the kernel.
    
    # -----------------------------------------------------------
    # Parse each line and generate the corresponding CUDA-Q code
    # -----------------------------------------------------------
    ko_line = 0
    for line in stim_lines:
        line = line.strip()
        
        # Comments
        match = re.match(r'^#(.*)', line)
        if match:
            output_lines.append(f"    #{match.group(1).strip()}")
            continue

        # DEPOLARIZE1
        match = re.match(r'^DEPOLARIZE1\((.*?)\)\s+(.*)', line)
        if match:
            output_lines.append(f"    ko = kraus_list[{ko_line}*{num_qubits}:({ko_line}+1)*{num_qubits}]")
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    beDepolarization1(ko[{num}], q[{num}])")
            ko_line += 1
            continue

        # T gate
        match = re.match(r'^T\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    t(q[{num}])")
            continue
            
        # H gate
        match = re.match(r'^H\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    h(q[{num}])")
            continue

        # X gate
        match = re.match(r'^X\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    x(q[{num}])")
            continue

        # Y gate
        match = re.match(r'^Y\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    y(q[{num}])")
            continue

        # Z gate
        match = re.match(r'^Z\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    z(q[{num}])")
            continue

        # RX gate
        match = re.match(r'^RX\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    rx({param}, q[{num}])")
            continue

        # RY gate
        match = re.match(r'^RY\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    ry({param}, q[{num}])")
            continue

        # RZ gate
        match = re.match(r'^RZ\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    rz({param}, q[{num}])")
            continue

        # C_XYZ Gate
        match = re.match(r'^C_XYZ\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    s(q[{num}])")
                output_lines.append(f"    s(q[{num}])")
                output_lines.append(f"    s(q[{num}])")
                output_lines.append(f"    h(q[{num}])")
            continue
            
        # DEPOLARIZE2
        match = re.match(r'^DEPOLARIZE2\((.*?)\)\s+(.*)', line)
        if match:
            output_lines.append(f"    ko = kraus_list[{ko_line}*{num_qubits}:({ko_line}+1)*{num_qubits}]")
            prob, indices_str = match.groups()
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    beDepolarization2(ko[{q1}], ko[{q2}], q[{q1}], q[{q2}])")
            ko_line += 1
            continue
            
        # CX (Controlled-X)
        match = re.match(r'^CX\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    x.ctrl(q[{q1}], q[{q2}])")
            continue

        # CY (Controlled-Y)
        match = re.match(r'^CY\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    y.ctrl(q[{q1}], q[{q2}])")
            continue

        # CZ (Controlled-Z)
        match = re.match(r'^CZ\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    z.ctrl(q[{q1}], q[{q2}])")
            continue

        # CH (Controlled-H)
        match = re.match(r'^CH\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    h.ctrl(q[{q1}], q[{q2}])")
            continue

        # CRX (Controlled-RX)
        match = re.match(r'^CRX\((.*?)\)\s+(.*)', line)
        if match:
            param, indices_str = match.groups()
            indices = re.findall(r'(\d+)\s+(\d+)', indices_str)
            for q1, q2 in indices:
                output_lines.append(f"    rx.ctrl({param}, q[{q1}], q[{q2}])")
            continue
            
        # X_ERROR
        match = re.match(r'^X_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            output_lines.append(f"    ko = kraus_list[{ko_line}*{num_qubits}:({ko_line}+1)*{num_qubits}]")
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    beXError(ko[{num}], q[{num}])")
            ko_line += 1
            continue

        # Y_ERROR
        match = re.match(r'^Y_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            output_lines.append(f"    ko = kraus_list[{ko_line}*{num_qubits}:({ko_line}+1)*{num_qubits}]")
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    beYError(ko[{num}], q[{num}])")
            ko_line += 1
            continue

        # Z_ERROR
        match = re.match(r'^Z_ERROR\((.*?)\)\s+(.*)', line)
        if match:
            output_lines.append(f"    ko = kraus_list[{ko_line}*{num_qubits}:({ko_line}+1)*{num_qubits}]")
            prob, indices_str = match.groups()
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    beZError(ko[{num}], q[{num}])")
            ko_line += 1
            continue

        # R Reset
        match = re.match(r'^R\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    reset(q[{num}])")
            continue
            
        # MR (Measure and Reset)
        match = re.match(r'^MR\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    mz(q[{num}])")
                output_lines.append(f"    reset(q[{num}])")
            continue
            
        # M (Measure)
        match = re.match(r'^M\s+(.*)', line)
        if match:
            indices_str = match.group(1)
            indices = re.findall(r'\S+', indices_str)
            for num in indices:
                output_lines.append(f"    mz(q[{num}])")
            continue
            
        # DETECTOR and OBSERVABLE_INCLUDE are non-native CUDA-Q ops.
        # We will comment them out for now.
        
        # DETECTOR
        match = re.match(r'^DETECTOR\((.*?)\)\s+(.*)', line)
        if match:
            det_loc, det_indices = match.groups()
            output_lines.append(f"    # stim.circuit.append('DETECTOR', [{det_indices}], [{det_loc}])")
            continue
            
        # OBSERVABLE_INCLUDE
        match = re.match(r'^OBSERVABLE_INCLUDE\((.*?)\)\s+(.*)', line)
        if match:
            obs_label, obs_indices = match.groups()
            output_lines.append(f"    # stim.circuit.append('OBSERVABLE_INCLUDE', [{obs_indices}], [{obs_label}])")
            continue

        # FORMALLY SKIPPING QUBIT_COORDS
        match = re.match(r'^QUBIT_COORDS\((.*?)\)\s+(.*)', line)
        if match:
            continue

        # FORMALLY SKIPPING SHIFT_COORDS
        match = re.match(r'^SHIFT_COORDS\((.*?)\)', line)
        if match:
            continue

        # FORMALLY SKIPPING TICKS
        match = re.match(r'^TICK', line)
        if match:
            continue

        # UNLISTED FUNCTION
        print('The following line is not listed: ' + line)

    # -----------------------------------------------------------
    # Add the main execution block
    # -----------------------------------------------------------
    output_lines.append("")
    output_lines.append("if __name__ == '__main__':")
    output_lines.append("    import pickle")
    output_lines.append("    from mpi4py import MPI")
    output_lines.append("    import os")
    output_lines.append("    import numpy as np")
    output_lines.append("")
    output_lines.append("    comm = MPI.COMM_WORLD")
    output_lines.append("    rank = comm.Get_rank()")
    output_lines.append("    cudaq.set_target('nvidia', option='mgpu,fp32')")
    output_lines.append("")
    output_lines.append("    run_file = 'error_sets.pickle'")
    output_lines.append("    output_directory = 'shot_sets'")
    output_lines.append("    os.makedirs(output_directory, exist_ok=True)")
    output_lines.append("    with open(run_file, 'rb') as file:")
    output_lines.append("        run_list = pickle.load(file)")
    output_lines.append("")
    output_lines.append("    for run in run_list:")
    output_lines.append("        serial_number = run[0]")
    output_lines.append("        kraus_ops = run[1]")
    output_lines.append("        run_shots = run[2]")
    output_lines.append("        filename = output_directory+'/ptsa_example_serialnumber_'+str(serial_number)+'.npy'")
    output_lines.append("        if not os.path.isfile(filename):")
    output_lines.append("            if rank == 0:")
    output_lines.append("                print('serial_number: ' + str(serial_number), flush=True)")
    output_lines.append("                print('Kraus operators: ' + str(kraus_ops), flush=True)")
    output_lines.append("                print('number of shots: ' + str(run_shots), flush=True)")
    output_lines.append("                print()")
    output_lines.append("")
    output_lines.append(f"            op_indices = [0 for _ in range(({ko_line}+1)*{num_qubits})]")
    output_lines.append(f"            for ko_op in kraus_ops:")
    output_lines.append(f"                temp_line, temp_qubits, temp_op_ints = ko_op")
    output_lines.append(f"                for temp_qubit in temp_qubits:")
    output_lines.append(f"                    op_indices[temp_line*{num_qubits}+temp_qubit] = temp_op_ints")
    output_lines.append("")
    output_lines.append(f"            noisy_counts = cudaq.sample(be_kernel, {num_qubits}, op_indices, shots_count=run_shots)")
    output_lines.append("            noisy_counts = dict(sorted(noisy_counts.items()))")
    output_lines.append("            np.save(filename, noisy_counts)")
    output_lines.append("            del op_indices, noisy_counts")
    output_lines.append("        del run, serial_number, kraus_ops, run_shots, filename")
    

    return "\n".join(output_lines)

def main():
    """Main function to handle command-line arguments and file processing."""
    parser = argparse.ArgumentParser(description='Convert a Stim circuit file to a CUDA-Q Python script.')
    parser.add_argument('input_file', help='Path to the input Stim file.')
    parser.add_argument('output_file', help='Path to the output CUDA-Q Python file. If not provided, output is sent to stdout.')
    parser.add_argument('num_qubits', help='Number of qubits')
    args = parser.parse_args()

    try:
        with open(args.input_file, 'r') as f:
            stim_lines = f.readlines()
    except FileNotFoundError:
        print(f"Error: Input file '{args.input_file}' not found.")
        sys.exit(1)

    python_script_content = process_stim_circuit(stim_lines, int(args.num_qubits))

    if args.output_file:
        try:
            with open(args.output_file, 'w') as f:
                f.write(python_script_content)
            print(f"Python output written to: {args.output_file}")
        except IOError as e:
            print(f"Error writing to output file '{args.output_file}': {e}")
            sys.exit(1)
    else:
        print(python_script_content)

if __name__ == '__main__':
    main()
